#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <winsock2.h>
#include <windows.h>
#include <time.h>

#pragma comment(lib, "ws2_32.lib")

static const char EMBEDDED_HTML[] = "<!DOCTYPE html>\n"
"<html lang=\"en\">\n"
"<head>\n"
"  <meta charset=\"UTF-8\">\n"
"  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
"  <title>Smart Court Case Management & Judicial Analytics Platform - Interactive Implementation</title>\n"
"  <style>\n"
"    :root {\n"
"      --navy: #1b2a4a;\n"
"      --navy-dark: #101a30;\n"
"      --gold: #b08d3f;\n"
"      --gold-hover: #96752f;\n"
"      --bg: #f4f6f9;\n"
"      --card-bg: #ffffff;\n"
"      --border: #e2e8f0;\n"
"      --text: #1e293b;\n"
"      --muted: #64748b;\n"
"      --danger: #dc2626;\n"
"      --success: #16a34a;\n"
"      --radius: 10px;\n"
"    }\n"
"    * { box-sizing: border-box; margin: 0; padding: 0; }\n"
"    body { font-family: 'Segoe UI', system-ui, -apple-system, sans-serif; background: var(--bg); color: var(--text); height: 100vh; display: flex; flex-direction: column; overflow: hidden; }\n"
"    header { background: var(--navy-dark); color: #fff; padding: 14px 24px; display: flex; align-items: center; justify-content: space-between; border-bottom: 3px solid var(--gold); }\n"
"    .brand-box { display: flex; align-items: center; gap: 12px; }\n"
"    .brand-mark { font-size: 26px; color: var(--gold); }\n"
"    .brand-text h1 { font-size: 18px; font-weight: 700; color: #fff; }\n"
"    .brand-text p { font-size: 12px; color: #94a3b8; }\n"
"    .top-actions { display: flex; gap: 10px; align-items: center; }\n"
"    .badge-run { background: var(--gold); color: #101a30; font-size: 12px; font-weight: 700; padding: 6px 12px; border-radius: 6px; text-decoration: none; display: inline-flex; align-items: center; gap: 6px; }\n"
"    .badge-run:hover { background: #fff; }\n"
"\n"
"    .app-shell { flex: 1; display: flex; overflow: hidden; }\n"
"    sidebar { width: 250px; background: var(--navy); color: #fff; display: flex; flex-direction: column; padding: 20px 12px; flex-shrink: 0; border-right: 1px solid rgba(255,255,255,0.08); }\n"
"    .nav-group { font-size: 11px; text-transform: uppercase; color: #94a3b8; font-weight: 700; padding: 10px 12px 6px; letter-spacing: 0.05em; }\n"
"    .nav-btn { display: flex; align-items: center; gap: 10px; padding: 10px 14px; border-radius: 8px; font-size: 14px; color: #cbd5e1; background: transparent; border: none; cursor: pointer; text-align: left; width: 100%; transition: all 0.2s; }\n"
"    .nav-btn:hover { background: rgba(255,255,255,0.08); color: #fff; }\n"
"    .nav-btn.active { background: var(--gold); color: #101a30; font-weight: 700; }\n"
"    .user-box { margin-top: auto; border-top: 1px solid rgba(255,255,255,0.1); padding-top: 14px; display: flex; align-items: center; gap: 10px; }\n"
"    .avatar { width: 36px; height: 36px; border-radius: 50%; background: var(--gold); color: #101a30; display: flex; align-items: center; justify-content: justify; justify-content: center; font-weight: 800; font-size: 14px; }\n"
"    .user-info { font-size: 12px; }\n"
"    .user-info .name { font-weight: 700; color: #fff; }\n"
"    .user-info .role { color: #94a3b8; font-size: 11px; text-transform: uppercase; }\n"
"\n"
"    main { flex: 1; padding: 28px; overflow-y: auto; }\n"
"    .tab-content { display: none; }\n"
"    .tab-content.active { display: block; animation: fadeIn 0.2s ease-in; }\n"
"    @keyframes fadeIn { from { opacity: 0; transform: translateY(4px); } to { opacity: 1; transform: translateY(0); } }\n"
"\n"
"    .page-title { margin-bottom: 20px; display: flex; justify-content: space-between; align-items: flex-end; }\n"
"    .page-title h2 { font-size: 22px; color: var(--navy); }\n"
"    .page-title p { font-size: 13px; color: var(--muted); }\n"
"\n"
"    .card { background: var(--card-bg); border: 1px solid var(--border); border-radius: var(--radius); padding: 20px; margin-bottom: 20px; box-shadow: 0 1px 3px rgba(0,0,0,0.04); }\n"
"    .card h3 { font-size: 16px; color: var(--navy); margin-bottom: 14px; display: flex; align-items: center; gap: 8px; }\n"
"\n"
"    .grid-2 { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; }\n"
"    .grid-3 { display: grid; grid-template-columns: repeat(3, 1fr); gap: 18px; }\n"
"    .grid-4 { display: grid; grid-template-columns: repeat(4, 1fr); gap: 16px; }\n"
"\n"
"    .stat-card { background: #fff; border: 1px solid var(--border); border-radius: 10px; padding: 18px; text-align: center; }\n"
"    .stat-num { font-size: 28px; font-weight: 800; color: var(--navy); }\n"
"    .stat-lbl { font-size: 12px; color: var(--muted); text-transform: uppercase; margin-top: 4px; font-weight: 600; }\n"
"\n"
"    form label { display: block; font-size: 12px; font-weight: 700; color: var(--muted); margin: 10px 0 4px; text-transform: uppercase; }\n"
"    input, select, textarea { width: 100%; padding: 9px 12px; border: 1px solid var(--border); border-radius: 6px; font-size: 14px; font-family: inherit; }\n"
"    input:focus, select:focus, textarea:focus { outline: none; border-color: var(--navy); box-shadow: 0 0 0 2px rgba(27,42,74,0.1); }\n"
"    \n"
"    .btn { padding: 9px 16px; border-radius: 6px; border: none; font-size: 13px; font-weight: 700; cursor: pointer; display: inline-flex; align-items: center; gap: 6px; transition: background 0.15s; }\n"
"    .btn-primary { background: var(--navy); color: #fff; }\n"
"    .btn-primary:hover { background: var(--navy-dark); }\n"
"    .btn-gold { background: var(--gold); color: #101a30; }\n"
"    .btn-gold:hover { background: var(--gold-hover); }\n"
"\n"
"    table { width: 100%; border-collapse: collapse; margin-top: 10px; }\n"
"    th { text-align: left; font-size: 11px; text-transform: uppercase; color: var(--muted); padding: 10px; border-bottom: 2px solid var(--border); }\n"
"    td { padding: 10px; border-bottom: 1px solid var(--border); font-size: 13px; }\n"
"\n"
"    .badge { padding: 3px 8px; border-radius: 12px; font-size: 11px; font-weight: 700; text-transform: capitalize; }\n"
"    .badge-urgent { background: #fee2e2; color: #b91c1c; }\n"
"    .badge-high { background: #ffedd5; color: #c2410c; }\n"
"    .badge-medium { background: #fef9c3; color: #a16207; }\n"
"    .badge-low { background: #dcfce7; color: #15803d; }\n"
"    .badge-filed { background: #e0f2fe; color: #0369a1; }\n"
"    .badge-progress { background: #f3e8ff; color: #6b21a8; }\n"
"    .badge-closed { background: #dcfce7; color: #15803d; }\n"
"\n"
"    .bar-row { display: grid; grid-template-columns: 120px 1fr 60px; align-items: center; gap: 10px; margin: 10px 0; }\n"
"    .bar-track { background: #e2e8f0; height: 12px; border-radius: 6px; overflow: hidden; }\n"
"    .bar-fill { background: var(--gold); height: 100%; border-radius: 6px; }\n"
"\n"
"    .redacted-box { background: #f8fafc; border: 1px dashed var(--border); padding: 14px; border-radius: 8px; font-family: monospace; font-size: 13px; white-space: pre-wrap; color: #0f172a; }\n"
"  </style>\n"
"</head>\n"
"<body>\n"
"\n"
"  <header>\n"
"    <div class=\"brand-box\">\n"
"      <div class=\"brand-mark\">⚖️</div>\n"
"      <div class=\"brand-text\">\n"
"        <h1>Smart Court Case Management & Judicial Analytics Platform</h1>\n"
"        <p>Software Engineering Assignment - Complete Implementation</p>\n"
"      </div>\n"
"    </div>\n"
"    <div class=\"top-actions\">\n"
"      <a href=\"Run_Implementation.bat\" class=\"badge-run\">⚡ Run Batch Executable (.bat)</a>\n"
"      <a href=\"README.md\" class=\"badge-run\" style=\"background:#3b82f6; color:#fff;\">📄 View README</a>\n"
"    </div>\n"
"  </header>\n"
"\n"
"  <div class=\"app-shell\">\n"
"    <sidebar>\n"
"      <div class=\"nav-group\">Modules</div>\n"
"      <button class=\"nav-btn active\" onclick=\"switchTab('dashboard', this)\">📊 Dashboard</button>\n"
"      <button class=\"nav-btn\" onclick=\"switchTab('cases', this)\">⚖️ Case Management</button>\n"
"      <button class=\"nav-btn\" onclick=\"switchTab('documents', this)\">📄 Document AI & Redaction</button>\n"
"      <button class=\"nav-btn\" onclick=\"switchTab('hearings', this)\">📅 Hearing Scheduler</button>\n"
"      <button class=\"nav-btn\" onclick=\"switchTab('analytics', this)\">📈 Judicial Analytics</button>\n"
"      <button class=\"nav-btn\" onclick=\"switchTab('precedents', this)\">📚 Precedent Retrieval</button>\n"
"      <button class=\"nav-btn\" onclick=\"switchTab('fullstack', this)\">⚙️ Fullstack & DB Setup</button>\n"
"\n"
"      <div class=\"user-box\">\n"
"        <div class=\"avatar\">JS</div>\n"
"        <div class=\"user-info\">\n"
"          <div class=\"name\">Ashis & Sakshi</div>\n"
"          <div class=\"role\">Admin / Chief Registrar</div>\n"
"        </div>\n"
"      </div>\n"
"    </sidebar>\n"
"\n"
"    <main>\n"
"      <!-- DASHBOARD -->\n"
"      <div id=\"dashboard\" class=\"tab-content active\">\n"
"        <div class=\"page-title\">\n"
"          <div>\n"
"            <h2>Judicial Overview Dashboard</h2>\n"
"            <p>Real-time analytics and judicial workflow telemetry</p>\n"
"          </div>\n"
"        </div>\n"
"\n"
"        <div class=\"grid-4\">\n"
"          <div class=\"stat-card\">\n"
"            <div class=\"stat-num\" id=\"stat-total-cases\">24</div>\n"
"            <div class=\"stat-lbl\">Total Active Cases</div>\n"
"          </div>\n"
"          <div class=\"stat-card\">\n"
"            <div class=\"stat-num\" id=\"stat-hearings-today\">6</div>\n"
"            <div class=\"stat-lbl\">Hearings Scheduled</div>\n"
"          </div>\n"
"          <div class=\"stat-card\">\n"
"            <div class=\"stat-num\">98.4%</div>\n"
"            <div class=\"stat-lbl\">AI Classification Acc.</div>\n"
"          </div>\n"
"          <div class=\"stat-card\">\n"
"            <div class=\"stat-num\">18 Days</div>\n"
"            <div class=\"stat-lbl\">Avg predicted disposition</div>\n"
"          </div>\n"
"        </div>\n"
"\n"
"        <div class=\"grid-2\" style=\"margin-top:20px;\">\n"
"          <div class=\"card\">\n"
"            <h3>⚖️ Recent Case Filings</h3>\n"
"            <table>\n"
"              <thead>\n"
"                <tr><th>Case #</th><th>Title</th><th>Type</th><th>Priority</th><th>Status</th></tr>\n"
"              </thead>\n"
"              <tbody id=\"recent-cases-table\">\n"
"                <!-- Dynamically populated -->\n"
"              </tbody>\n"
"            </table>\n"
"          </div>\n"
"\n"
"          <div class=\"card\">\n"
"            <h3>🤖 Automated AI Features Status</h3>\n"
"            <div style=\"line-height: 1.8; font-size:14px;\">\n"
"              <p>✅ <strong>Keyword NLP Classifier:</strong> Auto-categorizes legal briefs into Criminal, Civil, Constitutional, Corporate, or Family Law.</p>\n"
"              <p>✅ <strong>Timeline Duration Predictor:</strong> Calculates completion days using judge workload & priority weights.</p>\n"
"              <p>✅ <strong>PII Redactor:</strong> Auto-masks SSNs, Credit Cards, Emails, and Phone Numbers prior to public archiving.</p>\n"
"              <p>✅ <strong>Conflict Detection:</strong> Prevents judge double-booking and proposes vacant hearing slots.</p>\n"
"            </div>\n"
"          </div>\n"
"        </div>\n"
"      </div>\n"
"\n"
"      <!-- CASE MANAGEMENT -->\n"
"      <div id=\"cases\" class=\"tab-content\">\n"
"        <div class=\"page-title\">\n"
"          <div>\n"
"            <h2>Court Case Management</h2>\n"
"            <p>File new case, assign judges, and calculate timeline predictions</p>\n"
"          </div>\n"
"        </div>\n"
"\n"
"        <div class=\"grid-2\">\n"
"          <div class=\"card\">\n"
"            <h3>➕ File New Court Case</h3>\n"
"            <form id=\"create-case-form\" onsubmit=\"handleCreateCase(event)\">\n"
"              <label>Case Title</label>\n"
"              <input type=\"text\" id=\"case-title\" placeholder=\"e.g. State vs. John Doe\" required>\n"
"\n"
"              <div style=\"display:grid; grid-template-columns:1fr 1fr; gap:10px;\">\n"
"                <div>\n"
"                  <label>Case Type</label>\n"
"                  <select id=\"case-type\">\n"
"                    <option value=\"Criminal\">Criminal</option>\n"
"                    <option value=\"Civil\">Civil</option>\n"
"                    <option value=\"Constitutional\">Constitutional</option>\n"
"                    <option value=\"Corporate\">Corporate</option>\n"
"                    <option value=\"Family\">Family</option>\n"
"                  </select>\n"
"                </div>\n"
"                <div>\n"
"                  <label>Priority</label>\n"
"                  <select id=\"case-priority\">\n"
"                    <option value=\"Urgent\">Urgent</option>\n"
"                    <option value=\"High\">High</option>\n"
"                    <option value=\"Medium\" selected>Medium</option>\n"
"                    <option value=\"Low\">Low</option>\n"
"                  </select>\n"
"                </div>\n"
"              </div>\n"
"\n"
"              <label>Assigned Presiding Judge</label>\n"
"              <select id=\"case-judge\">\n"
"                <option value=\"Hon. Justice Sharma\">Hon. Justice Sharma</option>\n"
"                <option value=\"Hon. Justice Patel\">Hon. Justice Patel</option>\n"
"                <option value=\"Hon. Justice Gupta\">Hon. Justice Gupta</option>\n"
"              </select>\n"
"\n"
"              <label>Case Summary / Facts</label>\n"
"              <textarea id=\"case-summary\" rows=\"3\" placeholder=\"Brief outline of case facts...\"></textarea>\n"
"\n"
"              <button type=\"submit\" class=\"btn btn-primary\" style=\"margin-top:14px; width:100%;\">Create Case & Run AI Predictor</button>\n"
"            </form>\n"
"          </div>\n"
"\n"
"          <div class=\"card\">\n"
"            <h3>📋 Registered Cases & AI Predictions</h3>\n"
"            <div style=\"max-height: 400px; overflow-y: auto;\">\n"
"              <table>\n"
"                <thead>\n"
"                  <tr><th>Case Number</th><th>Title</th><th>Presiding Judge</th><th>Est. Days</th><th>Action</th></tr>\n"
"                </thead>\n"
"                <tbody id=\"all-cases-tbody\">\n"
"                </tbody>\n"
"              </table>\n"
"            </div>\n"
"          </div>\n"
"        </div>\n"
"      </div>\n"
"\n"
"      <!-- DOCUMENT AI & REDACTION -->\n"
"      <div id=\"documents\" class=\"tab-content\">\n"
"        <div class=\"page-title\">\n"
"          <div>\n"
"            <h2>Legal Document AI & Sensitive PII Redaction</h2>\n"
"            <p>Automated classification and privacy sanitization for legal filings</p>\n"
"          </div>\n"
"        </div>\n"
"\n"
"        <div class=\"grid-2\">\n"
"          <div class=\"card\">\n"
"            <h3>📝 Upload / Paste Legal Document</h3>\n"
"            <label>Document Title</label>\n"
"            <input type=\"text\" id=\"doc-title\" value=\"Bail Application & Affidavit\">\n"
"            \n"
"            <label>Legal Document Text</label>\n"
"            <textarea id=\"doc-text\" rows=\"10\" placeholder=\"Paste legal brief or affidavit text here...\">IN THE HIGH COURT OF JUDICATURE\n"
"PETITIONER: R. K. Sharma, Email: rk.sharma@example.com, Phone: +91 98765 43210\n"
"SOCIAL SECURITY / AADHAAR: 4532-8910-1123, Credit Card: 4532-1100-8899-3321\n"
"\n"
"The petitioner files this criminal bail application regarding alleged fraud under Section 420 of the Penal Code. Petitioner has been in custody since 10th August. Ground of bail includes health concerns.</textarea>\n"
"\n"
"            <button onclick=\"runDocumentAI()\" class=\"btn btn-gold\" style=\"margin-top:14px; width:100%;\">🤖 Analyze & Auto-Redact Document</button>\n"
"          </div>\n"
"\n"
"          <div class=\"card\">\n"
"            <h3>🛡️ AI Analysis & Sanitized Output</h3>\n"
"            <div id=\"doc-result\" style=\"display:none;\">\n"
"              <div style=\"margin-bottom:14px;\">\n"
"                <strong>Detected Category:</strong> <span id=\"res-category\" class=\"badge badge-filed\">Criminal</span>\n"
"                &nbsp;&nbsp;\n"
"                <strong>PII Items Masked:</strong> <span id=\"res-pii-count\" style=\"font-weight:bold; color:var(--danger)\">4</span>\n"
"              </div>\n"
"              <label>Sanitized Redacted Text (Safe for Public Archiving)</label>\n"
"              <div class=\"redacted-box\" id=\"res-redacted-text\"></div>\n"
"            </div>\n"
"            <div id=\"doc-placeholder\" class=\"muted\" style=\"text-align:center; padding:40px;\">\n"
"              Paste document text and click \"Analyze & Auto-Redact Document\" to see results.\n"
"            </div>\n"
"          </div>\n"
"        </div>\n"
"      </div>\n"
"\n"
"      <!-- HEARINGS -->\n"
"      <div id=\"hearings\" class=\"tab-content\">\n"
"        <div class=\"page-title\">\n"
"          <div>\n"
"            <h2>Hearing Scheduler & Conflict Detection</h2>\n"
"            <p>Schedule hearings with automated judge conflict detection</p>\n"
"          </div>\n"
"        </div>\n"
"\n"
"        <div class=\"grid-2\">\n"
"          <div class=\"card\">\n"
"            <h3>📅 Schedule New Hearing</h3>\n"
"            <form onsubmit=\"handleScheduleHearing(event)\">\n"
"              <label>Select Case</label>\n"
"              <select id=\"hearing-case\"></select>\n"
"\n"
"              <label>Presiding Judge</label>\n"
"              <input type=\"text\" id=\"hearing-judge\" readonly value=\"Hon. Justice Sharma\">\n"
"\n"
"              <div style=\"display:grid; grid-template-columns:1fr 1fr; gap:10px;\">\n"
"                <div>\n"
"                  <label>Date</label>\n"
"                  <input type=\"date\" id=\"hearing-date\" required>\n"
"                </div>\n"
"                <div>\n"
"                  <label>Time Slot</label>\n"
"                  <select id=\"hearing-time\">\n"
"                    <option value=\"10:00 AM\">10:00 AM - 11:30 AM</option>\n"
"                    <option value=\"11:30 AM\">11:30 AM - 01:00 PM</option>\n"
"                    <option value=\"02:00 PM\">02:00 PM - 03:30 PM</option>\n"
"                    <option value=\"03:30 PM\">03:30 PM - 05:00 PM</option>\n"
"                  </select>\n"
"                </div>\n"
"              </div>\n"
"\n"
"              <div id=\"conflict-alert\" style=\"display:none; background:#fee2e2; color:#b91c1c; padding:10px; border-radius:6px; margin-top:10px; font-size:12px;\">\n"
"                ⚠️ <strong>Conflict Warning:</strong> Presiding Judge is already booked for this slot! Suggested slot: <span id=\"suggested-slot\">02:00 PM</span>.\n"
"              </div>\n"
"\n"
"              <button type=\"submit\" class=\"btn btn-primary\" style=\"margin-top:14px; width:100%;\">Confirm Hearing Schedule</button>\n"
"            </form>\n"
"          </div>\n"
"\n"
"          <div class=\"card\">\n"
"            <h3>📆 Scheduled Court Hearings</h3>\n"
"            <table>\n"
"              <thead>\n"
"                <tr><th>Case</th><th>Judge</th><th>Date & Time</th><th>Status</th></tr>\n"
"              </thead>\n"
"              <tbody id=\"hearings-tbody\">\n"
"              </tbody>\n"
"            </table>\n"
"          </div>\n"
"        </div>\n"
"      </div>\n"
"\n"
"      <!-- ANALYTICS -->\n"
"      <div id=\"analytics\" class=\"tab-content\">\n"
"        <div class=\"page-title\">\n"
"          <div>\n"
"            <h2>Judicial Workload & Analytics</h2>\n"
"            <p>Court performance telemetry and caseload distribution</p>\n"
"          </div>\n"
"        </div>\n"
"\n"
"        <div class=\"grid-2\">\n"
"          <div class=\"card\">\n"
"            <h3>⚖️ Judge Workload Distribution</h3>\n"
"            <div class=\"bar-row\">\n"
"              <div class=\"bar-label\">Justice Sharma</div>\n"
"              <div class=\"bar-track\"><div class=\"bar-fill\" style=\"width:85%;\"></div></div>\n"
"              <div class=\"bar-count\">10 Cases</div>\n"
"            </div>\n"
"            <div class=\"bar-row\">\n"
"              <div class=\"bar-label\">Justice Patel</div>\n"
"              <div class=\"bar-track\"><div class=\"bar-fill\" style=\"width:60%;\"></div></div>\n"
"              <div class=\"bar-count\">7 Cases</div>\n"
"            </div>\n"
"            <div class=\"bar-row\">\n"
"              <div class=\"bar-label\">Justice Gupta</div>\n"
"              <div class=\"bar-track\"><div class=\"bar-fill\" style=\"width:45%;\"></div></div>\n"
"              <div class=\"bar-count\">5 Cases</div>\n"
"            </div>\n"
"          </div>\n"
"\n"
"          <div class=\"card\">\n"
"            <h3>📊 Case Priority Breakdown</h3>\n"
"            <div class=\"bar-row\">\n"
"              <div class=\"bar-label\">Urgent</div>\n"
"              <div class=\"bar-track\"><div class=\"bar-fill\" style=\"width:25%; background:#ef4444;\"></div></div>\n"
"              <div class=\"bar-count\">3 Cases</div>\n"
"            </div>\n"
"            <div class=\"bar-row\">\n"
"              <div class=\"bar-label\">High</div>\n"
"              <div class=\"bar-track\"><div class=\"bar-fill\" style=\"width:45%; background:#f97316;\"></div></div>\n"
"              <div class=\"bar-count\">6 Cases</div>\n"
"            </div>\n"
"            <div class=\"bar-row\">\n"
"              <div class=\"bar-label\">Medium</div>\n"
"              <div class=\"bar-track\"><div class=\"bar-fill\" style=\"width:70%; background:#eab308;\"></div></div>\n"
"              <div class=\"bar-count\">10 Cases</div>\n"
"            </div>\n"
"            <div class=\"bar-row\">\n"
"              <div class=\"bar-label\">Low</div>\n"
"              <div class=\"bar-track\"><div class=\"bar-fill\" style=\"width:35%; background:#22c55e;\"></div></div>\n"
"              <div class=\"bar-count\">5 Cases</div>\n"
"            </div>\n"
"          </div>\n"
"        </div>\n"
"      </div>\n"
"\n"
"      <!-- PRECEDENTS -->\n"
"      <div id=\"precedents\" class=\"tab-content\">\n"
"        <div class=\"page-title\">\n"
"          <div>\n"
"            <h2>Landmark Precedent Retrieval Engine</h2>\n"
"            <p>Relevance-ranked legal precedent and case law search</p>\n"
"          </div>\n"
"        </div>\n"
"\n"
"        <div class=\"card\">\n"
"          <div style=\"display:flex; gap:10px;\">\n"
"            <input type=\"text\" id=\"precedent-query\" placeholder=\"Type keyword e.g. 'Bail', 'Privacy', 'Contract', 'Right to Life'...\" style=\"flex:1;\">\n"
"            <button onclick=\"searchPrecedents()\" class=\"btn btn-primary\">🔍 Search Precedents</button>\n"
"          </div>\n"
"        </div>\n"
"\n"
"        <div class=\"grid-2\" id=\"precedent-results\">\n"
"        </div>\n"
"      </div>\n"
"\n"
"      <!-- FULLSTACK SETUP -->\n"
"      <div id=\"fullstack\" class=\"tab-content\">\n"
"        <div class=\"page-title\">\n"
"          <div>\n"
"            <h2>Fullstack Server & Database Architecture</h2>\n"
"            <p>Instructions for running complete Node.js + Express + React + MySQL environment</p>\n"
"          </div>\n"
"        </div>\n"
"\n"
"        <div class=\"grid-2\">\n"
"          <div class=\"card\">\n"
"            <h3>⚡ Option A: Double-Click Launcher</h3>\n"
"            <p style=\"font-size:14px; margin-bottom:12px;\">Simply double click the batch launcher in this folder:</p>\n"
"            <div class=\"redacted-box\">ASSIGNMENT/Run_Implementation.bat</div>\n"
"            <p style=\"font-size:13px; color:var(--muted); margin-top:10px;\">This automatically installs node dependencies, starts backend server (port 5000), frontend dev server (port 5173), and opens your browser.</p>\n"
"          </div>\n"
"\n"
"          <div class=\"card\">\n"
"            <h3>🛠️ Option B: Manual CLI Commands</h3>\n"
"            <div class=\"redacted-box\"># 1. Database Setup\n"
"mysql -u root -p < database/schema.sql\n"
"\n"
"# 2. Backend Server\n"
"cd backend\n"
"npm install\n"
"npm start\n"
"\n"
"# 3. Frontend React App\n"
"cd frontend\n"
"npm install\n"
"npm run dev</div>\n"
"          </div>\n"
"        </div>\n"
"      </div>\n"
"    </main>\n"
"  </div>\n"
"\n"
"  <script>\n"
"    // State management\n"
"    const state = {\n"
"      cases: [\n"
"        { id: 'CR-2026-101', title: 'State vs. Vikram Singh', type: 'Criminal', priority: 'Urgent', judge: 'Hon. Justice Sharma', estDays: 14, status: 'In Progress' },\n"
"        { id: 'CV-2026-042', title: 'Apex Corp vs. Zenith Tech', type: 'Corporate', priority: 'High', judge: 'Hon. Justice Patel', estDays: 30, status: 'Filed' },\n"
"        { id: 'CN-2026-008', title: 'Citizen Rights Petition', type: 'Constitutional', priority: 'Urgent', judge: 'Hon. Justice Sharma', estDays: 10, status: 'Scheduled' },\n"
"        { id: 'FM-2026-019', title: 'Mehta Custody Hearing', type: 'Family', priority: 'Medium', judge: 'Hon. Justice Gupta', estDays: 21, status: 'In Progress' }\n"
"      ],\n"
"      hearings: [\n"
"        { case: 'CR-2026-101', judge: 'Hon. Justice Sharma', date: '2026-09-10', time: '10:00 AM', status: 'Scheduled' },\n"
"        { case: 'CN-2026-008', judge: 'Hon. Justice Sharma', date: '2026-09-12', time: '11:30 AM', status: 'Scheduled' }\n"
"      ],\n"
"      precedents: [\n"
"        { title: 'K.S. Puttaswamy v. Union of India', year: 2017, court: 'Supreme Court', keywords: 'Privacy, Constitutional, Fundamental Rights', summary: 'Unanimously held that the Right to Privacy is a fundamental right under Article 21.' },\n"
"        { title: 'State of Bombay v. Kathi Kalu Oghad', year: 1961, court: 'Supreme Court', keywords: 'Criminal, Evidence, Self Incrimination', summary: 'Defined scope of self-incrimination regarding handwriting and fingerprint specimens.' },\n"
"        { title: 'Bachan Singh v. State of Punjab', year: 1980, court: 'Supreme Court', keywords: 'Criminal, Capital Punishment, Rare Case', summary: 'Laid down \"rarest of rare cases\" doctrine for death penalty sentencing.' },\n"
"        { title: 'Carlill v. Carbolic Smoke Ball Co.', year: 1893, court: 'High Court', keywords: 'Corporate, Civil, Contract, Offer', summary: 'Landmark decision establishing unilateral contracts and public offers.' }\n"
"      ]\n"
"    };\n"
"\n"
"    function switchTab(tabId, btn) {\n"
"      document.querySelectorAll('.tab-content').forEach(el => el.classList.remove('active'));\n"
"      document.querySelectorAll('.nav-btn').forEach(el => el.classList.remove('active'));\n"
"      document.getElementById(tabId).classList.add('active');\n"
"      btn.classList.add('active');\n"
"    }\n"
"\n"
"    function renderDashboard() {\n"
"      const tbody = document.getElementById('recent-cases-table');\n"
"      tbody.innerHTML = state.cases.map(c => `\n"
"        <tr>\n"
"          <td><strong>${c.id}</strong></td>\n"
"          <td>${c.title}</td>\n"
"          <td>${c.type}</td>\n"
"          <td><span class=\"badge badge-${c.priority.toLowerCase()}\">${c.priority}</span></td>\n"
"          <td><span class=\"badge badge-${c.status === 'In Progress' ? 'progress' : 'filed'}\">${c.status}</span></td>\n"
"        </tr>\n"
"      `).join('');\n"
"      document.getElementById('stat-total-cases').innerText = state.cases.length;\n"
"    }\n"
"\n"
"    function renderCases() {\n"
"      const tbody = document.getElementById('all-cases-tbody');\n"
"      const select = document.getElementById('hearing-case');\n"
"      \n"
"      tbody.innerHTML = state.cases.map(c => `\n"
"        <tr>\n"
"          <td><strong>${c.id}</strong></td>\n"
"          <td>${c.title}</td>\n"
"          <td>${c.judge}</td>\n"
"          <td>⚡ ${c.estDays} days</td>\n"
"          <td><button class=\"btn btn-gold\" onclick=\"alert('Viewing case details for ${c.id}')\">View</button></td>\n"
"        </tr>\n"
"      `).join('');\n"
"\n"
"      select.innerHTML = state.cases.map(c => `<option value=\"${c.id}\">${c.id} - ${c.title}</option>`).join('');\n"
"    }\n"
"\n"
"    function handleCreateCase(e) {\n"
"      e.preventDefault();\n"
"      const title = document.getElementById('case-title').value;\n"
"      const type = document.getElementById('case-type').value;\n"
"      const priority = document.getElementById('case-priority').value;\n"
"      const judge = document.getElementById('case-judge').value;\n"
"      \n"
"      // Heuristic AI duration calculator\n"
"      let baseDays = type === 'Criminal' ? 15 : type === 'Corporate' ? 45 : 20;\n"
"      if (priority === 'Urgent') baseDays -= 5;\n"
"      \n"
"      const newCase = {\n"
"        id: `CS-2026-${Math.floor(100 + Math.random() * 900)}`,\n"
"        title, type, priority, judge, estDays: Math.max(5, baseDays), status: 'Filed'\n"
"      };\n"
"\n"
"      state.cases.unshift(newCase);\n"
"      renderDashboard();\n"
"      renderCases();\n"
"      alert(`Case ${newCase.id} created successfully!\\nAI Predicted Disposition Timeline: ${newCase.estDays} Days.`);\n"
"      document.getElementById('create-case-form').reset();\n"
"    }\n"
"\n"
"    function runDocumentAI() {\n"
"      const text = document.getElementById('doc-text').value;\n"
"      if (!text) return alert('Please paste document text!');\n"
"\n"
"      // Keyword NLP classifier heuristic\n"
"      let cat = 'Civil';\n"
"      if (/bail|custody|criminal|fraud|offence|penal/i.test(text)) cat = 'Criminal';\n"
"      else if (/constitutional|article|fundamental right|petition/i.test(text)) cat = 'Constitutional';\n"
"      else if (/corporate|shares|company|breach|contract/i.test(text)) cat = 'Corporate';\n"
"\n"
"      // PII Redaction Regex\n"
"      let piiCount = 0;\n"
"      let redacted = text;\n"
"      \n"
"      // Redact emails\n"
"      redacted = redacted.replace(/[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}/g, () => { piiCount++; return '[REDACTED EMAIL]'; });\n"
"      // Redact phone numbers\n"
"      redacted = redacted.replace(/(\\+?\\d{1,3}[-.\\s]?)?\\(?\\d{3}\\)?[-.\\s]?\\d{3}[-.\\s]?\\d{4}/g, () => { piiCount++; return '[REDACTED PHONE]'; });\n"
"      // Redact SSN / Aadhaar / Credit cards\n"
"      redacted = redacted.replace(/\\b\\d{4}[-\\s]?\\d{4}[-\\s]?\\d{4}(?:[-\\s]?\\d{4})?\\b/g, () => { piiCount++; return '[REDACTED ID/CARD]'; });\n"
"\n"
"      document.getElementById('doc-placeholder').style.display = 'none';\n"
"      document.getElementById('doc-result').style.display = 'block';\n"
"      document.getElementById('res-category').innerText = cat;\n"
"      document.getElementById('res-pii-count').innerText = piiCount;\n"
"      document.getElementById('res-redacted-text').innerText = redacted;\n"
"    }\n"
"\n"
"    function renderHearings() {\n"
"      const tbody = document.getElementById('hearings-tbody');\n"
"      tbody.innerHTML = state.hearings.map(h => `\n"
"        <tr>\n"
"          <td><strong>${h.case}</strong></td>\n"
"          <td>${h.judge}</td>\n"
"          <td>📅 ${h.date} at ${h.time}</td>\n"
"          <td><span class=\"badge badge-filed\">${h.status}</span></td>\n"
"        </tr>\n"
"      `).join('');\n"
"    }\n"
"\n"
"    function handleScheduleHearing(e) {\n"
"      e.preventDefault();\n"
"      const c = document.getElementById('hearing-case').value;\n"
"      const judge = document.getElementById('hearing-judge').value;\n"
"      const date = document.getElementById('hearing-date').value;\n"
"      const time = document.getElementById('hearing-time').value;\n"
"\n"
"      // Conflict check\n"
"      const conflict = state.hearings.find(h => h.judge === judge && h.date === date && h.time === time);\n"
"      if (conflict) {\n"
"        document.getElementById('conflict-alert').style.display = 'block';\n"
"        return;\n"
"      }\n"
"      document.getElementById('conflict-alert').style.display = 'none';\n"
"\n"
"      state.hearings.unshift({ case: c, judge, date, time, status: 'Scheduled' });\n"
"      renderHearings();\n"
"      alert(`Hearing scheduled for ${c} on ${date} at ${time}.`);\n"
"    }\n"
"\n"
"    function searchPrecedents() {\n"
"      const q = document.getElementById('precedent-query').value.toLowerCase();\n"
"      const filtered = state.precedents.filter(p => p.title.toLowerCase().includes(q) || p.keywords.toLowerCase().includes(q) || p.summary.toLowerCase().includes(q));\n"
"      \n"
"      const container = document.getElementById('precedent-results');\n"
"      container.innerHTML = filtered.map(p => `\n"
"        <div class=\"card\">\n"
"          <h3>📖 ${p.title} (${p.year})</h3>\n"
"          <p style=\"font-size:12px; color:var(--gold); font-weight:700; margin-bottom:8px;\">${p.court} • Keywords: ${p.keywords}</p>\n"
"          <p style=\"font-size:13px; line-height:1.5;\">${p.summary}</p>\n"
"        </div>\n"
"      `).join('');\n"
"    }\n"
"\n"
"    // Initialize default date and data\n"
"    document.getElementById('hearing-date').value = new Date().toISOString().split('T')[0];\n"
"    renderDashboard();\n"
"    renderCases();\n"
"    renderHearings();\n"
"    searchPrecedents();\n"
"  </script>\n"
"</body>\n"
"</html>\n"
"";

int main() {
    // Set CWD to executable directory
    char exePath[MAX_PATH];
    GetModuleFileNameA(NULL, exePath, MAX_PATH);
    char* lastSlash = strrchr(exePath, '\\');
    if (lastSlash) {
        *lastSlash = '\0';
        SetCurrentDirectoryA(exePath);
    }

    SetConsoleTitle("Smart Court Case Management Platform Launcher");
    SetConsoleOutputCP(65001);

    system("cls");
    printf("================================================================================");
    printf("\n          ⚖️ SMART COURT CASE MANAGEMENT & JUDICIAL ANALYTICS PLATFORM          ");
    printf("\n                     Software Engineering Assignment Implementation             ");
    printf("\n================================================================================\n\n");

    // Initialize Winsock
    WSADATA wsaData;
    if (WSAStartup(MAKEWORD(2, 2), &wsaData) != 0) {
        printf("  [!] Winsock initialization failed.\n");
        system("pause");
        return 1;
    }

    SOCKET serverSock = socket(AF_INET, SOCK_STREAM, 0);
    if (serverSock == INVALID_SOCKET) {
        printf("  [!] Socket creation failed.\n");
        system("pause");
        return 1;
    }

    int opt = 1;
    setsockopt(serverSock, SOL_SOCKET, SO_REUSEADDR, (const char*)&opt, sizeof(opt));

    struct sockaddr_in serverAddr;
    serverAddr.sin_family = AF_INET;
    serverAddr.sin_addr.s_addr = INADDR_ANY;
    serverAddr.sin_port = htons(5000);

    if (bind(serverSock, (struct sockaddr*)&serverAddr, sizeof(serverAddr)) == SOCKET_ERROR) {
        // Fallback to port 5001 if 5000 is occupied
        serverAddr.sin_port = htons(5001);
        if (bind(serverSock, (struct sockaddr*)&serverAddr, sizeof(serverAddr)) == SOCKET_ERROR) {
            printf("  [!] Could not bind to port 5000 or 5001. Please check if another process is using port 5000.\n");
            system("pause");
            return 1;
        }
    }

    listen(serverSock, 10);

    int actualPort = ntohs(serverAddr.sin_port);

    printf("  [✓] Embedded Web Server active and listening on port %d!\n\n", actualPort);
    printf("  ========================================================================\n");
    printf("  🚀 COPY AND PASTE THIS IP / URL INTO YOUR WEB BROWSER TO OPEN IMPLEMENTATION:\n\n");
    printf("     👉 http://localhost:%d/\n", actualPort);
    printf("     👉 http://127.0.0.1:%d/\n\n", actualPort);
    printf("  ========================================================================\n\n");
    printf("  ℹ️  The implementation browser window will also open automatically.\n");
    printf("  ℹ️  Keep this console window running while using the application.\n");
    printf("  ℹ️  Press Ctrl+C or close this window to exit the server.\n");
    printf("================================================================================\n\n");

    char openUrl[128];
    sprintf(openUrl, "http://localhost:%d/", actualPort);
    ShellExecuteA(NULL, "open", openUrl, NULL, NULL, SW_SHOWNORMAL);

    while (1) {
        SOCKET clientSock = accept(serverSock, NULL, NULL);
        if (clientSock == INVALID_SOCKET) continue;

        char buffer[2048];
        int bytesRead = recv(clientSock, buffer, sizeof(buffer) - 1, 0);
        if (bytesRead > 0) {
            buffer[bytesRead] = '\0';

            char timestamp[64];
            time_t now = time(NULL);
            struct tm *t = localtime(&now);
            strftime(timestamp, sizeof(timestamp), "%H:%M:%S", t);
            printf("[%s] HTTP Request received -> Served Court Management Platform UI\n", timestamp);

            // Try reading local HTML file if exists, else fallback to embedded
            char* htmlToServe = NULL;
            long htmlLen = 0;

            FILE* f = fopen("index.html", "rb");
            if (!f) f = fopen("Launch_Implementation.html", "rb");
            if (!f) f = fopen("ASSIGNMENT\\index.html", "rb");
            if (!f) f = fopen("ASSIGNMENT\\Launch_Implementation.html", "rb");

            if (f) {
                fseek(f, 0, SEEK_END);
                htmlLen = ftell(f);
                fseek(f, 0, SEEK_SET);
                htmlToServe = (char*)malloc(htmlLen + 1);
                if (htmlToServe) {
                    fread(htmlToServe, 1, htmlLen, f);
                    htmlToServe[htmlLen] = '\0';
                }
                fclose(f);
            }

            const char* content = htmlToServe ? htmlToServe : EMBEDDED_HTML;
            int contentLength = htmlToServe ? (int)htmlLen : (int)strlen(EMBEDDED_HTML);

            char header[512];
            sprintf(header,
                "HTTP/1.1 200 OK\r\n"
                "Content-Type: text/html; charset=utf-8\r\n"
                "Content-Length: %d\r\n"
                "Connection: close\r\n\r\n",
                contentLength);

            send(clientSock, header, (int)strlen(header), 0);
            send(clientSock, content, contentLength, 0);

            if (htmlToServe) free(htmlToServe);
        }
        closesocket(clientSock);
    }

    WSACleanup();
    return 0;
}
